export const NEW_DICTIONARY = 'NEW_DICTIONARY';
export const UPDATE_DICTIONARY = 'UPDATE_DICTIONARY';
export const DELETE_DICTIONARY = 'DELETE_DICTIONARY';
export const SELECT_DICTIONARY = 'SELECT_DICTIONARY';
export const CHANGE_VIEW = 'CHANGE_VIEW';